# Generated by Django 3.2.7 on 2022-02-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentet', '0002_auto_20211229_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AcademicTitle',
                'verbose_name_plural': 'AcademicTitles',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('year_of_study', models.IntegerField()),
                ('group', models.CharField(max_length=5)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('link', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('left_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentet.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentet.program')),
                ('study_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentet.studylevel')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentet.department')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('office', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/academic')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('link', models.CharField(max_length=1000)),
                ('bio', models.CharField(max_length=1000)),
                ('education', models.CharField(max_length=1000)),
                ('science_article', models.CharField(max_length=1000)),
                ('scientific_research', models.CharField(max_length=1000)),
                ('activities', models.CharField(max_length=1000)),
                ('social_links', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('left_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('academic_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.academictitle')),
                ('courses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentet.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentet.department')),
            ],
            options={
                'verbose_name': 'Academic',
                'verbose_name_plural': 'Academics',
            },
        ),
    ]
